### ISSUE TITLE
Update local Drupal Docker image

### ISSUE THREAD

**Issue by back-2-95** [City-of-Helsinki/drupal-helfi-platform#42]
To support ARM on upcoming Macs on local development, please update:

`DRUPAL_IMAGE=druidfi/drupal:8.0-web` to `DRUPAL_IMAGE=druidfi/drupal-web:php-8.0`in `.env` file.

It is the same image but build both for intel and arm.

**Comment by tuutti** [comment]
Is there some technical limitation (or some other reason) why the `drupal:8.0-web` image couldn't be build for both? It would be much easier if we didn't have to instruct everyone to update their projects to use different image.

**Comment by back-2-95** [comment]
If you update your project with new image, it's then just `make fresh` away from updating. No need for "extra" pulling etc.

If I'd update old tags with new image, some projects would have the new image not by their choice but mine. So that's why in this order.

Noting also that using 8.x tag vs. 8.x.xx in local is good, but if those images are used in production envs then use 8.x.xx tags to prevent updates from Hub.

**Comment by tuutti** [comment]
All projects were updated today to use `https://github.com/orgs/City-of-Helsinki/packages/container/package/drupal-web`  which is built on top of  `druidfi/drupal-web:php-8.0`.
